replicaCount: 1
image:
  repository: ghcr.io/catie-aq/REPO_NAME
  pullPolicy: Always
  tag: "main"

imagePullSecrets:
  - name: ghcr-credential
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
