name: Update pre-commit and template


on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/autoupdate-pre-commit.yml@main
